### ISSUE TITLE
Model checkpoints are not available 

### ISSUE THREAD

**Issue by MikeLasz** [ajiljalal/code-cs-fairness#3]
The `download.sh` script attempts to download, among other things, model checkpoints. 
However, the provided [StyleGAN checkpoints](https://drive.google.com/uc?id=1I4KtMsW61nRI6TOaadpA5m_6Ygd4QrgR) and the [ncsnv2 checkpoint](https://drive.google.com/uc?id=1jDcIxI0nqv6AOBhHpgbH7OIW63QU77lh) are not available anymore. 
While the ncsnv2 checkpoint is available through the [official repository](https://github.com/ermongroup/ncsnv2/tree/1bcea03bd97d76a8357b9d674fa0bae5ff0f1093), it is difficult (and not completely clear how) to retrain the exact StyleGAN2 models. I guess you had been using the configurations given by the official NVIDIA [StyleGAN-Repo](https://github.com/NVlabs/stylegan3/blob/main/docs/configs.md) for the AFHQ-experiments, is this correct?  
Is it still possible to provide the StyleGAN checkpoints?  

Best regards
Mike

**Comment by ajiljalal** [comment]
Apologies, I lost my drive access after graduating.

I've pushed changes with updated links, lmk if it still doesn't work.

**Comment by MikeLasz** [comment]
Awesome, it worked! Thank you.
